
- name: Fetch Node.js installation script
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_lts.x
    dest: /tmp/setup_lts.x

- name: Execute installation script
  become: true
  ansible.builtin.shell: sudo -E bash /tmp/setup_lts.x

- name: Install Node.js LTS from apt
  become: true
  ansible.builtin.apt:
    name: nodejs
    update_cache: yes

- name: Install n with npm
  become: true
  community.general.npm:
    name: "n"
    global: true
    state: present

- name: Switch to Node.js 13.8.0
  become: true
  ansible.builtin.shell: |
    sudo n 13.8.0

- name: Install PM2 Process Manager with npm
  become: true
  community.general.npm:
    name: "pm2"
    global: true
    state: present
